### ISSUE TITLE
Add simulation and show result of a contract interaction in metamask

### ISSUE THREAD

**Issue by louislucrypto** [0xFacet/facet-vm#1]
Metamask Snaps https://docs.metamask.io/snaps/ supports a way to add plugin into metamask wallet. 
Assume we have a API endpoints we could call before user send out dumb contract transaction and show result in metamaks wallet that could be a good UX. 

https://github.com/MetaMask/snaps/discussions/675

**Comment by RogerPodacter** [comment]
Great feedback, thank you! Transaction simulation will be out shortly and we'll work on Snaps!

**Comment by RogerPodacter** [comment]
Simulation is OUT!

https://github.com/ethscriptions-protocol/ethscriptions-vm-api/pull/3

Next step is the SNAP
