### ISSUE TITLE
Rubidity Sandbox @ Secure Ruby  - Idea Is To "Break-up" Rubidity Into Modules (Gems) For Easy (Re)use

### ISSUE THREAD

**Issue by geraldb** [0xFacet/facet-vm#10]
Sorry if this is the wrong channel -  fyi: i am big fan of rubidity (and also a long time fan / programmer of ruby) and, thus, i have started a rubidity sandbox to start to experiment with the published ethscriptions vm source and make the rubidity contract language more accessible and reusable. still early. see here -> <https://github.com/s6ruby/rubidity> if anyone wants to join in.  

ps: the first "project" / idea is to rework (break-out) the typed language (state/storage) machinery into a reusable library (gem) e.g. rubidity-typed or such.  note: i am a random nobody with a budget of zero, thus, expect slow progress (but yes, all work / experiments are open source).

**Comment by RogerPodacter** [comment]
I love it! I wrote a reply [in the Discord](https://discord.com/channels/1119430005869522965/1119430007283007529/1150063427167997993) which I will duplicate here!

I think your idea is dope! We definitely need off-chain for testing the on-chain and we have the start of a decent solution here: https://github.com/ethscriptions-protocol/ethscriptions-vm-server/blob/main/app/models/contract_test_helper.rb#L42. If you call this method you don't have to know anything about the chain. But right now this is only for testing purposes. In order for a user to deploy and call DCs in their browser etc they need to use Goerli and we should change this!

I also agree that the importance of this tech goes beyond blockchain applications, but I try to keep most grandiose thoughts to myself.

I definitely agree that we should extract Rubidity into its own gem; it's definitely a mess now.

Finally, BIG QUESTION: do you know how we could create a "sandbox"-type thing that we could use to prevent DCs from infinite loops in a deterministic (ie gas-based not time-based) way? If we could do this we could run arbitrary DCs which would actually finally be "game over"!

**Comment by geraldb** [comment]
wow. thanks for the respone. to also copy from discord:

Wow. thanks for the welcome. i wasn't really expecting any answers.   and wow. thanks for all the info and updates. 

> Finally, BIG QUESTION: do you know how we could create a "sandbox"-type thing...

timeouts / time-based is the first idea that pops up

> deterministic (ie gas-based not time-based) 

but i see - if you want to go with ethereum vm style counting of bytcode instructions / operations using a ruby vm than that's not impossible but i guess sound like hard-core engineering work (a starting point might be looking into mruby - the "tiny" ruby  see here -> <https://mruby.org> or <https://github.com/mruby/mruby>   that might be easier to work with than "classic/ big" cruby).
or maybe "delegate" the sandbox - and try to use something with containers or other operating systems (os) services that meter usage not by time but compute resources or such ( sorry - not really an expert on containers and "compute virtualization & metering"  here).   and yeah sorry i don't have a magic silver bullet for the big question.   again thanks for the welcome.  amazing and insprining work on ethscriptions. keep it up.   greeetings from (near) vienna, austria.
