### ISSUE TITLE
ERROR -- : Max array length is 25 (RuntimeError)

### ISSUE THREAD

**Issue by cebook** [0xFacet/facet-vm#120]
Hi
When I synchronize to block height 18707543, bundle exec clockwork config/processor_clock.rb displays the following error:

I, [2023-12-05T06:22:42.098108 #2377784]  INFO -- : Finished 'EthBlock.process_contract_actions_until_done' duration_ms=97 error=#<RuntimeError: Max array length is 25>
I, [2023-12-05T06:22:43.001287 #2377784]  INFO -- : Triggering 'EthBlock.process_contract_actions_until_done'
E, [2023-12-05T06:22:43.101056 #2377784] ERROR -- : Max array length is 25 (RuntimeError)
/opt/eths/facet-vm/lib/rubidity/type_system/array_variable.rb:72:in `[]='
/opt/eths/facet-vm/lib/rubidity/type_system/array_variable.rb:91:in `push'
/opt/eths/facet-vm/lib/rubidity/type_system/typed_variable.rb:93:in `method_missing'
FacetSwapV1Factory:307:in `block (2 levels) in instance_eval_with_isolation'
/opt/eths/facet-vm/lib/rubidity/contract_functions/function_context.rb:29:in `define_and_call_function_method'
/opt/eths/facet-vm/lib/rubidity/contract_functions/abi_proxy.rb:80:in `block (3 levels) in define_function_method'
/opt/eths/facet-vm/lib/rubidity/state_management/state_proxy.rb:23:in `detecting_changes'
/opt/eths/facet-vm/lib/rubidity/contract_functions/abi_proxy.rb:79:in `block (2 levels) in define_function_method'
/opt/eths/facet-vm/lib/rubidity/contract_implementation.rb:243:in `public_send'
/opt/eths/facet-vm/lib/rubidity/contract_implementation.rb:243:in `call'
/opt/eths/facet-vm/lib/rubidity/contract_implementation.rb:243:in `public_send'
/opt/eths/facet-vm/app/models/contract.rb:72:in `block in execute_function'
/opt/eths/facet-vm/app/models/contract.rb:90:in `with_correct_implementation'
/opt/eths/facet-vm/app/models/contract.rb:58:in `execute_function'
/opt/eths/facet-vm/app/models/contract_call.rb:31:in `execute!'
/opt/eths/facet-vm/lib/rubidity/transaction_execution/call_stack.rb:72:in `execute_in_frame'
/opt/eths/facet-vm/lib/rubidity/transaction_execution/call_stack.rb:53:in `block in execute_in_new_frame'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.1.2/lib/active_support/current_attributes.rb:214:in `set'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.1.2/lib/active_support/current_attributes.rb:156:in `set'
/opt/eths/facet-vm/lib/rubidity/transaction_execution/call_stack.rb:52:in `execute_in_new_frame'
/opt/eths/facet-vm/lib/rubidity/type_system/contract_variable.rb:54:in `method_missing'
/opt/eths/facet-vm/lib/rubidity/type_system/contract_variable.rb:11:in `method_missing'
FacetSwapV1Router:334:in `block (2 levels) in instance_eval_with_isolation'
/opt/eths/facet-vm/lib/rubidity/contract_functions/function_context.rb:29:in `define_and_call_function_method'
/opt/eths/facet-vm/lib/rubidity/contract_functions/abi_proxy.rb:80:in `block (3 levels) in define_function_method'
/opt/eths/facet-vm/lib/rubidity/state_management/state_proxy.rb:23:in `detecting_changes'
/opt/eths/facet-vm/lib/rubidity/contract_functions/abi_proxy.rb:79:in `block (2 levels) in define_function_method'
/opt/eths/facet-vm/lib/rubidity/contract_implementation.rb:247:in `call'
/opt/eths/facet-vm/lib/rubidity/contract_implementation.rb:247:in `send'
/opt/eths/facet-vm/lib/rubidity/contract_functions/function_context.rb:11:in `method_missing'
FacetSwapV1Router:354:in `block (2 levels) in instance_eval_with_isolation'
/opt/eths/facet-vm/lib/rubidity/contract_functions/function_context.rb:29:in `define_and_call_function_method'
/opt/eths/facet-vm/lib/rubidity/contract_functions/abi_proxy.rb:80:in `block (3 levels) in define_function_method'
/opt/eths/facet-vm/lib/rubidity/state_management/state_proxy.rb:23:in `detecting_changes'
/opt/eths/facet-vm/lib/rubidity/contract_functions/abi_proxy.rb:79:in `block (2 levels) in define_function_method'
/opt/eths/facet-vm/lib/rubidity/contract_implementation.rb:243:in `public_send'
/opt/eths/facet-vm/lib/rubidity/contract_implementation.rb:243:in `call'
/opt/eths/facet-vm/lib/rubidity/contract_implementation.rb:243:in `public_send'
/opt/eths/facet-vm/app/models/contract.rb:70:in `block in execute_function'
/opt/eths/facet-vm/app/models/contract.rb:90:in `with_correct_implementation'
/opt/eths/facet-vm/app/models/contract.rb:58:in `execute_function'
/opt/eths/facet-vm/app/models/contract_call.rb:31:in `execute!'
/opt/eths/facet-vm/lib/rubidity/transaction_execution/call_stack.rb:72:in `execute_in_frame'
/opt/eths/facet-vm/lib/rubidity/transaction_execution/call_stack.rb:53:in `block in execute_in_new_frame'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.1.2/lib/active_support/current_attributes.rb:214:in `set'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.1.2/lib/active_support/current_attributes.rb:156:in `set'
/opt/eths/facet-vm/lib/rubidity/transaction_execution/call_stack.rb:52:in `execute_in_new_frame'
/opt/eths/facet-vm/app/models/contract_transaction.rb:249:in `block in make_initial_call'
/opt/eths/facet-vm/app/models/contract_transaction.rb:241:in `block in with_global_context'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.1.2/lib/active_support/current_attributes.rb:214:in `set'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.1.2/lib/active_support/current_attributes.rb:156:in `set'
/opt/eths/facet-vm/app/models/contract_transaction.rb:228:in `with_global_context'
/opt/eths/facet-vm/app/models/contract_transaction.rb:246:in `make_initial_call'
/opt/eths/facet-vm/app/models/contract_transaction.rb:268:in `execute_transaction'
/opt/eths/facet-vm/app/models/contract_transaction.rb:30:in `block in create_from_ethscription!'
<internal:kernel>:90:in `tap'
/opt/eths/facet-vm/app/models/contract_transaction.rb:29:in `create_from_ethscription!'
/opt/eths/facet-vm/app/models/ethscription.rb:47:in `block in process!'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:342:in `transaction'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.1.2/lib/active_record/transactions.rb:212:in `transaction'
/opt/eths/facet-vm/app/models/ethscription.rb:36:in `process!'
/opt/eths/facet-vm/app/models/eth_block.rb:81:in `block (2 levels) in process_contract_actions_for_next_block_with_ethscriptions'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.1.2/lib/active_record/relation/delegation.rb:100:in `each'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.1.2/lib/active_record/relation/delegation.rb:100:in `each'
/opt/eths/facet-vm/app/models/eth_block.rb:80:in `block in process_contract_actions_for_next_block_with_ethscriptions'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/transaction.rb:535:in `block in within_new_transaction'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.1.2/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/transaction.rb:532:in `within_new_transaction'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:344:in `transaction'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.1.2/lib/active_record/transactions.rb:212:in `transaction'
/opt/eths/facet-vm/app/models/eth_block.rb:66:in `process_contract_actions_for_next_block_with_ethscriptions'
/opt/eths/facet-vm/app/models/eth_block.rb:33:in `block in process_contract_actions_until_done'
/opt/eths/facet-vm/app/models/eth_block.rb:30:in `loop'
/opt/eths/facet-vm/app/models/eth_block.rb:30:in `process_contract_actions_until_done'
/opt/eths/facet-vm/config/processor_clock.rb:25:in `block in <module:Clockwork>'
/usr/local/rvm/gems/ruby-3.2.2/gems/clockwork-3.0.2/lib/clockwork/event.rb:61:in `execute'
/usr/local/rvm/gems/ruby-3.2.2/gems/clockwork-3.0.2/lib/clockwork/event.rb:48:in `run'
/usr/local/rvm/gems/ruby-3.2.2/gems/clockwork-3.0.2/lib/clockwork/manager.rb:136:in `block in tick'
/usr/local/rvm/gems/ruby-3.2.2/gems/clockwork-3.0.2/lib/clockwork/manager.rb:134:in `each'
/usr/local/rvm/gems/ruby-3.2.2/gems/clockwork-3.0.2/lib/clockwork/manager.rb:134:in `tick'
/usr/local/rvm/gems/ruby-3.2.2/gems/clockwork-3.0.2/lib/clockwork/manager.rb:123:in `block (2 levels) in run_tick_loop'
/usr/local/rvm/gems/ruby-3.2.2/gems/clockwork-3.0.2/lib/clockwork/manager.rb:121:in `synchronize'
/usr/local/rvm/gems/ruby-3.2.2/gems/clockwork-3.0.2/lib/clockwork/manager.rb:121:in `block in run_tick_loop'

**Comment by cebook** [comment]
The above error was resolved when I changed the 
MAX_ARRAY_LENGTH=25 
in lib\rubidity\type_system\array_variable.rb 
to a larger value.
But a new mistake was made:

bundle exec clockwork config/processor_clock.rb
I, [2023-12-05T08:28:52.697115 #2515332]  INFO -- : Starting clock for 1 events: [ EthBlock.process_contract_actions_until_done ]
I, [2023-12-05T08:28:52.698853 #2515332]  INFO -- : Triggering 'EthBlock.process_contract_actions_until_done'
E, [2023-12-05T08:28:53.312999 #2515332] ERROR -- : undefined method `assign_attributes' for nil:NilClass (NoMethodError)
/opt/eths/facet-vm/app/models/contract_call.rb:58:in `block in assign_contract'
<internal:kernel>:90:in `tap'
/opt/eths/facet-vm/app/models/contract_call.rb:57:in `assign_contract'
/opt/eths/facet-vm/app/models/contract_call.rb:50:in `rescue in execute!'
/opt/eths/facet-vm/app/models/contract_call.rb:22:in `execute!'
/opt/eths/facet-vm/lib/rubidity/transaction_execution/call_stack.rb:72:in `execute_in_frame'
/opt/eths/facet-vm/lib/rubidity/transaction_execution/call_stack.rb:53:in `block in execute_in_new_frame'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.1.2/lib/active_support/current_attributes.rb:214:in `set'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.1.2/lib/active_support/current_attributes.rb:156:in `set'
/opt/eths/facet-vm/lib/rubidity/transaction_execution/call_stack.rb:52:in `execute_in_new_frame'
/opt/eths/facet-vm/lib/rubidity/contract_implementation.rb:366:in `new'
/opt/eths/facet-vm/lib/rubidity/contract_implementation.rb:247:in `call'
/opt/eths/facet-vm/lib/rubidity/contract_implementation.rb:247:in `send'
/opt/eths/facet-vm/lib/rubidity/contract_functions/function_context.rb:11:in `method_missing'
FacetSwapV1Factory:303:in `block (2 levels) in instance_eval_with_isolation'
/opt/eths/facet-vm/lib/rubidity/contract_functions/function_context.rb:29:in `define_and_call_function_method'
/opt/eths/facet-vm/lib/rubidity/contract_functions/abi_proxy.rb:80:in `block (3 levels) in define_function_method'
/opt/eths/facet-vm/lib/rubidity/state_management/state_proxy.rb:23:in `detecting_changes'
/opt/eths/facet-vm/lib/rubidity/contract_functions/abi_proxy.rb:79:in `block (2 levels) in define_function_method'
/opt/eths/facet-vm/lib/rubidity/contract_implementation.rb:243:in `public_send'
/opt/eths/facet-vm/lib/rubidity/contract_implementation.rb:243:in `call'
/opt/eths/facet-vm/lib/rubidity/contract_implementation.rb:243:in `public_send'
/opt/eths/facet-vm/app/models/contract.rb:72:in `block in execute_function'
/opt/eths/facet-vm/app/models/contract.rb:90:in `with_correct_implementation'
/opt/eths/facet-vm/app/models/contract.rb:58:in `execute_function'
/opt/eths/facet-vm/app/models/contract_call.rb:31:in `execute!'
/opt/eths/facet-vm/lib/rubidity/transaction_execution/call_stack.rb:72:in `execute_in_frame'
/opt/eths/facet-vm/lib/rubidity/transaction_execution/call_stack.rb:53:in `block in execute_in_new_frame'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.1.2/lib/active_support/current_attributes.rb:214:in `set'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.1.2/lib/active_support/current_attributes.rb:156:in `set'
/opt/eths/facet-vm/lib/rubidity/transaction_execution/call_stack.rb:52:in `execute_in_new_frame'
/opt/eths/facet-vm/lib/rubidity/type_system/contract_variable.rb:54:in `method_missing'
/opt/eths/facet-vm/lib/rubidity/type_system/contract_variable.rb:11:in `method_missing'
FacetSwapV1Router:334:in `block (2 levels) in instance_eval_with_isolation'
/opt/eths/facet-vm/lib/rubidity/contract_functions/function_context.rb:29:in `define_and_call_function_method'
/opt/eths/facet-vm/lib/rubidity/contract_functions/abi_proxy.rb:80:in `block (3 levels) in define_function_method'
/opt/eths/facet-vm/lib/rubidity/state_management/state_proxy.rb:23:in `detecting_changes'
/opt/eths/facet-vm/lib/rubidity/contract_functions/abi_proxy.rb:79:in `block (2 levels) in define_function_method'
/opt/eths/facet-vm/lib/rubidity/contract_implementation.rb:247:in `call'
/opt/eths/facet-vm/lib/rubidity/contract_implementation.rb:247:in `send'
/opt/eths/facet-vm/lib/rubidity/contract_functions/function_context.rb:11:in `method_missing'
FacetSwapV1Router:354:in `block (2 levels) in instance_eval_with_isolation'
/opt/eths/facet-vm/lib/rubidity/contract_functions/function_context.rb:29:in `define_and_call_function_method'
/opt/eths/facet-vm/lib/rubidity/contract_functions/abi_proxy.rb:80:in `block (3 levels) in define_function_method'
/opt/eths/facet-vm/lib/rubidity/state_management/state_proxy.rb:23:in `detecting_changes'
/opt/eths/facet-vm/lib/rubidity/contract_functions/abi_proxy.rb:79:in `block (2 levels) in define_function_method'
/opt/eths/facet-vm/lib/rubidity/contract_implementation.rb:243:in `public_send'
/opt/eths/facet-vm/lib/rubidity/contract_implementation.rb:243:in `call'
/opt/eths/facet-vm/lib/rubidity/contract_implementation.rb:243:in `public_send'
/opt/eths/facet-vm/app/models/contract.rb:70:in `block in execute_function'
/opt/eths/facet-vm/app/models/contract.rb:90:in `with_correct_implementation'
/opt/eths/facet-vm/app/models/contract.rb:58:in `execute_function'
/opt/eths/facet-vm/app/models/contract_call.rb:31:in `execute!'
/opt/eths/facet-vm/lib/rubidity/transaction_execution/call_stack.rb:72:in `execute_in_frame'
/opt/eths/facet-vm/lib/rubidity/transaction_execution/call_stack.rb:53:in `block in execute_in_new_frame'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.1.2/lib/active_support/current_attributes.rb:214:in `set'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.1.2/lib/active_support/current_attributes.rb:156:in `set'
/opt/eths/facet-vm/lib/rubidity/transaction_execution/call_stack.rb:52:in `execute_in_new_frame'
/opt/eths/facet-vm/app/models/contract_transaction.rb:249:in `block in make_initial_call'
/opt/eths/facet-vm/app/models/contract_transaction.rb:241:in `block in with_global_context'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.1.2/lib/active_support/current_attributes.rb:214:in `set'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.1.2/lib/active_support/current_attributes.rb:156:in `set'
/opt/eths/facet-vm/app/models/contract_transaction.rb:228:in `with_global_context'
/opt/eths/facet-vm/app/models/contract_transaction.rb:246:in `make_initial_call'
/opt/eths/facet-vm/app/models/contract_transaction.rb:268:in `execute_transaction'
/opt/eths/facet-vm/app/models/contract_transaction.rb:30:in `block in create_from_ethscription!'
<internal:kernel>:90:in `tap'
/opt/eths/facet-vm/app/models/contract_transaction.rb:29:in `create_from_ethscription!'
/opt/eths/facet-vm/app/models/ethscription.rb:47:in `block in process!'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:342:in `transaction'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.1.2/lib/active_record/transactions.rb:212:in `transaction'
/opt/eths/facet-vm/app/models/ethscription.rb:36:in `process!'
/opt/eths/facet-vm/app/models/eth_block.rb:81:in `block (2 levels) in process_contract_actions_for_next_block_with_ethscriptions'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.1.2/lib/active_record/relation/delegation.rb:100:in `each'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.1.2/lib/active_record/relation/delegation.rb:100:in `each'
/opt/eths/facet-vm/app/models/eth_block.rb:80:in `block in process_contract_actions_for_next_block_with_ethscriptions'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/transaction.rb:535:in `block in within_new_transaction'
/usr/local/rvm/gems/ruby-3.2.2/gems/activesupport-7.1.2/lib/active_support/concurrency/null_lock.rb:9:in `synchronize'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/transaction.rb:532:in `within_new_transaction'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.1.2/lib/active_record/connection_adapters/abstract/database_statements.rb:344:in `transaction'
/usr/local/rvm/gems/ruby-3.2.2/gems/activerecord-7.1.2/lib/active_record/transactions.rb:212:in `transaction'
/opt/eths/facet-vm/app/models/eth_block.rb:66:in `process_contract_actions_for_next_block_with_ethscriptions'
/opt/eths/facet-vm/app/models/eth_block.rb:33:in `block in process_contract_actions_until_done'
/opt/eths/facet-vm/app/models/eth_block.rb:30:in `loop'
/opt/eths/facet-vm/app/models/eth_block.rb:30:in `process_contract_actions_until_done'
/opt/eths/facet-vm/config/processor_clock.rb:25:in `block in <module:Clockwork>'
/usr/local/rvm/gems/ruby-3.2.2/gems/clockwork-3.0.2/lib/clockwork/event.rb:61:in `execute'
/usr/local/rvm/gems/ruby-3.2.2/gems/clockwork-3.0.2/lib/clockwork/event.rb:48:in `run'
/usr/local/rvm/gems/ruby-3.2.2/gems/clockwork-3.0.2/lib/clockwork/manager.rb:136:in `block in tick'
/usr/local/rvm/gems/ruby-3.2.2/gems/clockwork-3.0.2/lib/clockwork/manager.rb:134:in `each'
/usr/local/rvm/gems/ruby-3.2.2/gems/clockwork-3.0.2/lib/clockwork/manager.rb:134:in `tick'
/usr/local/rvm/gems/ruby-3.2.2/gems/clockwork-3.0.2/lib/clockwork/manager.rb:123:in `block (2 levels) in run_tick_loop'
/usr/local/rvm/gems/ruby-3.2.2/gems/clockwork-3.0.2/lib/clockwork/manager.rb:121:in `synchronize'
/usr/local/rvm/gems/ruby-3.2.2/gems/clockwork-3.0.2/lib/clockwork/manager.rb:121:in `block in run_tick_loop'

**Comment by cebook** [comment]
Hi @RogerPodacter 
Please help me check the above mistakes, thank you very much.

**Comment by RogerPodacter** [comment]
If you pull the latest changes from main it should fix both of these and will not require a reindex!

**Comment by cebook** [comment]
I pulled the latest code, there's no problem, thank you very much.
Tom.
