### ISSUE TITLE
Remove Liquidity  FETH / ETHS

### ISSUE THREAD

**Issue by liulaocai18** [0xFacet/facet-vm#131]
FacetSwapV1Pair02 error: FacetSwapV1: INSUFFICIENT_LIQUIDITY_BURNED. (FacetSwapV1Pair02:206)

**Comment by xifengxx** [comment]
I encountered the same issue and cannot withdraw LP liquidity.

**Comment by youxiroy18** [comment]
cannot withdraw, it is so bad
