### ISSUE TITLE
facetswap fetch_ethscriptions stuck at block 18873515

### ISSUE THREAD

**Issue by seaify** [0xFacet/facet-vm#143]
```
3.2.2 :013 > EthscriptionSync.fetch_ethscriptions(18873514, max_blocks: 1)
  Ethscription Count (19.5ms)  SELECT COUNT(*) FROM "ethscriptions" WHERE (block_number < 18873514)
 => {"error"=>{"message"=>"Count is off"}} 
```

the website and facet-vm have stop works for more than 14 hours

@mikeahirsch @RogerPodacter @hyppocritez

**Comment by dubuqingfeng** [comment]
+1, stuck at block 18929411

**Comment by RogerPodacter** [comment]
Sorry about this; due to an edge case you'll need to do `EthBlock.where("block_number >= 18914353").delete_all` and reindex from there (which should happen automatically).

We are going to create a new mechanism for notifying people about changes like this!

**Comment by RogerPodacter** [comment]
For future updates please join this TG Group! https://t.me/facetvm
