### ISSUE TITLE
Contract implementations as data

### ISSUE THREAD

**Issue by RogerPodacter** [0xFacet/facet-vm#35]
Currently we get a contract's implementation logic like this:

```ruby
class Contract < ApplicationRecord
  def implementation
    # type == "UniswapV2Pair" etc
    "Contracts::#{self.type}".constantize.new(self)
  end
end
```

This links the contract's implementation to the global state of the VM server. This means that code changes that should be retroactive (such as bug fixes) can be mixed in with code changes that should not (contract upgrades). This also means that contract implementations could be accidentally changed at runtime since contract classes are accessible from all scopes.

Furthermore, from a security standpoint it links the ability to update a contract implementation with the ability to commit to the git repository, which is also not so great.

Finally, this means that contract implementations must adhere to the rules of Rails constants, which means they must be classes, in certain folders, etc. This is not so great because classes do not exist in Rubidity.

Instead, we should treat contracts as "data," i.e., as strings of Ruby code. These could be files on disk or even strings in a Dumb Contract's storage. We would have much more control over their exact format this way. Here is an example.

```ruby
contract StubERC20, is: [ERC20, Ownable] do
  constructor(name: :string) {
    ERC20.constructor(name: name, symbol: "symbol", decimals: 18)
  }
  
  function :mint, { amount: :uint256 }, :public do
    _mint(to: msg.sender, amount: amount)
  end
end
```

Then, to get a contract record's implementation, we eval the stand-alone code in a context independent of the VM app's global state:

```ruby
module ContractBuilder
  class ContractBuilderTypeError < StandardError; end
  
  def self.build_implementation_instance_from_code_string(code_string, contract_record)
    # Could also use BasicObject here and define the methods we want to expose
    # Manually. This would be more secure, but more work.
    builder = Module.new.extend(self)
    implementation_class = builder.module_eval(code_string)

    implementation_class.get_instance_for(contract_record)
  end

  def const_missing(name)
    name.to_sym
  end

  def contract(name, is: [], &block)
    implementation_class = Class.new(ContractImplementation) do
      singleton_class.class_eval do
        is.each do |ancestor|
          # The implementation of `is` would have to change as well since it currently
          # looks for parents in the global "Contracts::" scope
          is(ancestor)
        end
      end
    end
    
    implementation_class.tap do |klass|
      klass.instance_eval(&block)
    
      def klass.get_instance_for(contract_record)
        if name == contract_record.type
          new(contract_record)
        else
          raise ContractBuilderTypeError, "Contract type #{contract_record.type}"
        end
      end
    end
  end
end

class Contract < ApplicationRecord
  def get_implementation_from_code_string(code_string)
    ContractBuilder.build_implementation_instance_from_code_string(code_string, self)
  end
end

dummy_code_string = <<-CODE
  contract StubERC20, is: [ERC20, Ownable] do
    constructor(name: :string) {
      ERC20.constructor(name: name, symbol: "symbol", decimals: 18)
    }
    
    function :mint, { amount: :uint256 }, :public do
      _mint(to: msg.sender, amount: amount)
    end
  end
CODE

Contract.first.get_implementation_from_code_string(dummy_code_string)
```

This way we can "lock in" a contract version as the contents of a specific stand-alone file, versus whatever a certain global constant (e.g., `Contracts::StubERC20`) in our application happens to resolve to.

As a side benefit it would give us a way to write more Solidity-esque code!

Semi-relatedly, dumping this here for the moment as the above is related to the idea of "upgrading contract implementations"

```ruby
class Contracts::SystemContractUpgradeManager < ContractImplementation
  mapping ({address: :address}), :public, :contractAdmins
  
  constructor() {}
  
  function :getContractAdmin, { contract: :address }, :public, :view, returns: :address do
    contractAdmins[contract] == address(0) ?
      esc.magicFunctionGetDeployerOf(contract) :
      contractAdmins[contract]
  end
  
  function :updateContractAdmin, { contract: :address, newAdmin: :address }, :public, returns: :bool do
    require(
      getContractAdmin(contract) == msg.sender,
      'Only the current admin can update the admin'
    )
    
    s.contractAdmins[contract] = newAdmin
    
    return true
  end
  
  function :upgradeContract, { contract: :address }, :public, returns: :bool do
    require(
      getContractAdmin(contract) == msg.sender,
      'Only the admin can upgrade the contract'
    )
    
    esc.magicFunctionUpgradeContractToLatestVersion(contract)
  end
  
  function :upgradeContractAndExecuteMigration, { contract: :address, migrationData: :string }, :public do
    # TODO: add a call()-equivalent so a contract can call another contract
    # without having to explicitly know the function signature.
    # We could probably use a JSON string
    
    require(upgradeContract(contract), "Failed to upgrade contract")
    
    esc.magicFunctionCallContractMigration(contract, migrationData)
  end
end
```

**Comment by geraldb** [comment]
for reference / background (i - gerald bauer am the (alternate) rubidity gem / modular version code monkey / programmer - see <https://github.com/s6ruby/rubidity>.

i am 100% with you keeping the contract source in a (frozen) string (with a crypto hash / finger print for security / reproducability and such) and  loading (the source string/text) via database or whatever.  

i also love the idea of (built-in) support for upgradable (or versioned) contracts  (with "in-place" code replacement and "automagically" (re)using the contract storage / state by (re)using the same contract address or such). keep up the great work. 


> Currently we get a contract's implementation logic like this:
>
>      # ... 
>      Contracts::#{self.type}".constantize.new(self)

in the modular rubidity gem version i removed `constantize`   
and all contract types are always "eager-loaded" ruby classes (not symbols or strings) - might be a good issue / ticket for a rubidity language proposal / update ;-) - 
for sure i am with you removing the "default" (or required?) `Contracts::` namespace - 
i removed `Contracts::` from day one ;-) - 
the idea is use whatever (not something "dictated" by rails zeitwerk auto-loading convention or such). Big fan or rails but there's a good point to make to keep rubidity (core) "off-rails"  without any rails-y or activesupport "magic" required / depending on. 

Otherwise, i am still learning and catching-up with your code.  keep going. love it all.
