### ISSUE TITLE
Loop with upper iteration limit

### ISSUE THREAD

**Issue by RogerPodacter** [0xFacet/facet-vm#69]
Because we do not yet have the concept of gas, we cannot have unbounded loops. For example, in the swap function of the UniswapV2Router:

```ruby
function :_swap, {
  amounts: [:uint256],
  path: [:address],
  _to: :address
}, :internal, :virtual do
  for i in 0...(path.length - 1)
    input, output = path[i], path[i + 1]
    token0, _ = sortTokens(input, output)
    amountOut = amounts[i + 1]
    amount0Out, amount1Out = input == token0 ? [0, amountOut] : [amountOut, 0]
    to = i < path.length - 2 ? pairFor(factory, output, path[i + 2]) : _to

    UniswapV2Pair(pairFor(factory, input, output)).swap(amount0Out, amount1Out, to, "")
  end
  
  return nil
end
```

User can create arbitrarily long `path` arrays and so this loop is unbounded. How can we give it an upper limit? I propose a new function called `limited_loop`. It would work like this:

```ruby
function :_swap, {
  amounts: [:uint256],
  path: [:address],
  _to: :address
}, :internal, :virtual do
  limited_loop(
    start: 0,
    condition: ->(i) { i < path.length - 1 },
    step: 1,
    max_iterations: 10
  ) do |i|
    input, output = path[i], path[i + 1]
    token0, _ = sortTokens(input, output)
    amountOut = amounts[i + 1]
    amount0Out, amount1Out = input == token0 ? [0, amountOut] : [amountOut, 0]
    to = i < path.length - 2 ? pairFor(factory, output, path[i + 2]) : _to
  
    UniswapV2Pair(pairFor(factory, input, output)).swap(amount0Out, amount1Out, to, "")
  end
  
  return nil
end
```

It is more verbose but it's good to be explicit with loops because they are dangerous. Also the current `for i in 0...(path.length - 1)` thing is pretty confusing, even if it is terse.

Here is a potential implementation for `limited_loop`:

```ruby
def limited_loop(start:, condition:, step:, max_iterations:)
  raise ArgumentError, 'Block is required' unless block_given?

  if singleton_class.method_defined?(:continue)
    raise StandardError, "The method 'continue' is already defined"
  end

  define_singleton_method(:continue) do
    throw :skip_iteration
  end

  current_val = start
  iteration_count = 0

  while condition.call(current_val) && iteration_count < max_iterations
    catch(:skip_iteration) do
      yield(current_val)
    end

    current_val += step
    iteration_count += 1
  end

  if condition.call(current_val)
    raise StandardError, "MaxIterationsExceeded"
  end

  singleton_class.undef_method(:continue)
end
```

**Comment by geraldb** [comment]
if i may comment -   i support all new (rubidity) language constructs / experiments and yes, this looks practical.     

i am personally not a fan of gas (instruction counting / metering) but believe it must be possible to have "deterministic" timeouts to handle the halting problem / infinite loops in turning complete code. one proposal / idea is to make in stage 1 your indexer the definite source for timeouts all other indexers have to / MUST follow  - until something more distributed / decentralized gets worked out. I am opptimistic, that is, i assume timeout are rare (if you are not under attack) and maybe less than 0.1% of transactions.  as always i might be wrong.  sorry for thinking out loud. keep up the great work on facet / rubidity.
