### ISSUE TITLE
rubidity idea / lang improvement proposal - turn type symbols (e.g. :uint256, :string, :address, etc) into "plain" uint256, string, address, etc. via type helpers

### ISSUE THREAD

**Issue by geraldb** [0xFacet/facet-vm#72]
hello,

here's a small idea / proposal to improve readability of rubidity o.g. / classic syntax by turning type symbols 
(e.g. :uint256, :string, :address, etc) into "plain" uint256, string, address, etc. via type helpers.

Let's try to the PublicMintERC20 contract as example - before:

```ruby
contract :PublicMintERC20, is: :ERC20 do
  uint256 :public, :maxSupply
  uint256 :public, :perMintLimit
  
  constructor(
    name: :string,
    symbol: :string,
    maxSupply: :uint256,
    perMintLimit: :uint256,
    decimals: :uint8
  ) do 
    # ...
  end
  
  
  function :mint, { amount: :uint256 }, :public do
    # ...
  end
  
  function :airdrop, { to: :address, amount: :uint256 }, :public do
    # ...
  end
end
```

and after:

```ruby
contract :PublicMintERC20, is: :ERC20 do
  uint256 :public, :maxSupply
  uint256 :public, :perMintLimit
  
  constructor(
    name: string,
    symbol: string,
    maxSupply: uint256,
    perMintLimit: uint256,
    decimals: uint8
  ) do 
    # ...
  end
  
  
  function :mint, { amount: uint256 }, :public do
    # ...
  end
  
  function :airdrop, { to: address, amount: uint256 }, :public do
    # ...
  end
end
```

how is this possible?  add to the (storage) value type helpers in the body a check if args is zero (0) and return the type symbol. example:

``` ruby
 [:string, 
    :uint8, :uint32, :uint112, :uint256,
    :address
   ].each do |type|
     define_method(type) do |*args|

        if args.size == 0
           ## assume type helper to convert :string to string, 
           ##                               :address to address, and such
           puts "  turn :#{type} into #{type}"
           return type
        end 
      # ...
  end
end
```

Anyways, as always keep up the great work on rubidity and sorry for taking up your time.  note: i have only tried small contract samples, thus, i might be missing some edge cases (or conflict with "global conversion functions" or such).

**Comment by RogerPodacter** [comment]
Great suggestion! We'd need to do something fancier with the method as we have `address(0)` already so we can't redefine it but overall it seems like a great move. Backwards compatible also since the method can just return the symbol as in your example.

**Comment by geraldb** [comment]
Good point. Thanks for taking the time as always. Yes I understand. For reference - I was posting the code to add only to the (auto-generated) type helpers. Here's the full monty from inside the class ContractImplementation:

before

``` ruby
Type.value_types.each do |type|
    define_singleton_method(type) do |*args|
      define_state_variable(type, args)
    end
  end
```

after

``` ruby
Type.value_types.each do |type|
    define_singleton_method(type) do |*args|
       if args.size == 0
           ## assume type helper to convert :string to string, 
           ##                               :address to address, and such
           puts "  turn :#{type} into #{type}"
           return type
        end 
       define_state_variable(type, args)
    end
  end
```
