### ISSUE TITLE
I can't withdraw my geth from Facet

### ISSUE THREAD

**Issue by lostpinky** [0xFacet/facet-vm#73]
When I click **initiate withdrawal**， I can execute my first transaction successfully. But strangely no second transaction option pops up. So actually I just inscribed a piece of json on goerli , nothing happens other than that. No geth goes into my wallet but it should be.

**Comment by RogerPodacter** [comment]
Can you send an Etherscan link to your tx? We will look into it!

**Comment by RogerPodacter** [comment]
We see the problem and are working on a fix!

**Comment by panlinhui1234** [comment]
Hello! I just tested facetswap and everything else is very good, but it cannot remove lp, and it also needs to be removed as a whole, not in part

> We see the problem and are working on a fix!

Hello! I just tested facetswap and everything else is very good, but it cannot remove lp, and it also needs to be removed as a whole, not in part

**Comment by panlinhui1234** [comment]
Hello! I just tested facetswap and everything else is very good, but it cannot remove lp, and it also needs to be removed as a whole, not in part

**Comment by panlinhui1234** [comment]
Hello! I just tested facetswap and everything else is very good, but it cannot remove lp, and it also needs to be removed as a whole, not in part
