### ISSUE TITLE
Migration error

### ISSUE THREAD

**Issue by lutian12** [0xFacet/facet-vm#77]
Hello, I would like to inquire about your version of PostgreSQL. I encountered an error while migrating the database architecture:
== 20230824165302 CreateEthscriptions: migrating ==============================
-- create_table(:ethscriptions)
   -> 0.0491s
-- execute("      CREATE OR REPLACE FUNCTION delete_later_ethscriptions()\n      RETURNS TRIGGER AS $$\n      BEGIN\n        DELETE FROM ethscriptions WHERE block_number > OLD.block_number OR (block_number = OLD.block_number AND transaction_index > OLD.transaction_index);\n        RETURN OLD;\n      END;\n      $$ LANGUAGE plpgsql;\n\n      CREATE TRIGGER trigger_delete_later_ethscriptions\n      AFTER DELETE ON ethscriptions\n      FOR EACH ROW EXECUTE FUNCTION delete_later_ethscriptions();\n")
bin/rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::SyntaxError: ERROR:  syntax error at or near "FUNCTION"
LINE 11:       FOR EACH ROW EXECUTE FUNCTION delete_later_ethscriptio...
                                    ^
/server/facet-vm/db/migrate/20230824165302_create_ethscriptions.rb:32:in `up'

Caused by:
ActiveRecord::StatementInvalid: PG::SyntaxError: ERROR:  syntax error at or near "FUNCTION"
LINE 11:       FOR EACH ROW EXECUTE FUNCTION delete_later_ethscriptio...
                                    ^
/server/facet-vm/db/migrate/20230824165302_create_ethscriptions.rb:32:in `up'

Caused by:
PG::SyntaxError: ERROR:  syntax error at or near "FUNCTION"
LINE 11:       FOR EACH ROW EXECUTE FUNCTION delete_later_ethscriptio...
                                    ^
/server/facet-vm/db/migrate/20230824165302_create_ethscriptions.rb:32:in `up'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by RogerPodacter** [comment]
Interesting! What version of postgresql are you running? I believe we need 15 or higher.

Also can you try this on the `rc1` branch? That is our "release candidate" where we have made a lot of changes and will be merging into `main` next week.

I assume this is a migration from a blank db?
